#!/bin/bash

PREF="$HOME"
if [ "$(uname -o)" == 'Cygwin' ] ; then
    PREF="$APPDATA"
fi

AUTHLIB_DIR="$PREF/.minecraft/libraries/com/mojang/authlib/"

rm -rf "$AUTHLIB_DIR"/*

echo "Patched libraries are now deleted. Restart Minecraft to restore libraries to original versions."
