#!/bin/bash

RED='\033[0;31m'
NC='\033[0m'

APPDIR=~/mcbuild
LIBDIR=~/libhelper

if [ "$(uname -o)" == 'Cygwin' ] ; then
    IGNORE_ATTR="-c core.filemode=false"
fi

cd "$LIBDIR"
git $IGNORE_ATTR pull && make

cd "$APPDIR"
if [ "x$1" != 'x' ] ; then
    if [ "$1" == 'dev' ] ; then
        BRANCH="master"
    else
        BRANCH="release_$1"
    fi
    git $IGNORE_ATTR checkout "$BRANCH" || ( echo "Failed to check out branch $BRANCH" ; exit 1 )
fi

git $IGNORE_ATTR pull && make clean && make && make install

printf "${RED}MCBuild updated${NC}\n"
