#!/bin/bash

if [ "$(uname -o)" == 'Cygwin' ] ; then
    IGNORE_ATTR="-c core.filemode=false"
fi

cd ~/libhelper
git $IGNORE_ATTR pull && make

cd ~/mcbuild
git $IGNORE_ATTR pull && make

echo "MCBuild updated"

