#!/bin/bash

if [ -z "$APPDATA" ]; then APPDATA="$HOME" ; fi
AUTHLIB_DIR="$APPDATA/.minecraft/libraries/com/mojang/authlib/"

ORIG_URL="https://sessionserver.mojang.com/session/minecraft/join"
MOD_URL="http://127.0.0.1:8080/sssssssssssssssssssssssssssssssss"

TMP_DIR="/tmp/auth"
TMP_CLASS="$TMP_DIR/com/mojang/authlib/yggdrasil/YggdrasilMinecraftSessionService.class"

cd "$AUTHLIB_DIR"

for ver in * ; do
    AUTHLIB_JAR="$AUTHLIB_DIR/$ver/authlib-$ver.jar"
    AUTHLIB_SHA="$AUTHLIB_JAR.sha"

    unzip -d "$TMP_DIR" "$AUTHLIB_JAR" > /dev/null
    cat "$TMP_CLASS" | sed -b "s#$ORIG_URL#$MOD_URL#" > "$TMP_CLASS.new"
    mv "$TMP_CLASS.new" "$TMP_CLASS"
    cd "$TMP_DIR"
    zip -r "$AUTHLIB_JAR" * > /dev/null
    cd -
    rm -rf "$TMP_DIR"

    sha1sum "$AUTHLIB_JAR" | sed 's#\\##' | awk '{ print $1 }' > "$AUTHLIB_SHA"
done

echo "Libraries are now patched for use with MCBuild. Run mcb_remove to restore the original state"

